github: [andisearch]
buy_me_a_coffee: andisearch
custom: ["https://www.paypal.me/lazyweb", "https://www.paypal.com/donate?business=angela%40lazyweb.ai&no_recurring=0&item_name=Support+Andi&currency_code=USD"]